apiVersion: v1
kind: Service
metadata:
  name: {{ include "ssd-service.fullname" . }}
  labels:
    {{- include "ssd-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
      name: http
